import {
    Employee, LeaveRequest, KPI, PayrollRecord, DailyAttendance,
    ShiftTemplate, RosterAssignment, CompanySettings, Announcement,
    SkillRequirement, PTKPStatus
} from '@/types';

// ========================
// DEFAULT COMPANY SETTINGS
// ========================

export const defaultCompanySettings: CompanySettings = {
    companyName: 'PT Worker Indonesia',
    companyAddress: 'Jl. Sudirman No. 1, Jakarta Selatan 12190',
    companyPhone: '021-5555-0000',
    companyEmail: 'info@worker.co.id',
    companyNpwp: '01.234.567.8-012.000',
    workDays: [1, 2, 3, 4, 5], // Mon-Fri
    defaultWorkStart: '08:00',
    defaultWorkEnd: '17:00',
    // BPJS Rates
    bpjsKesEmployeeRate: 0.01,
    bpjsKesEmployerRate: 0.04,
    bpjsJhtEmployeeRate: 0.02,
    bpjsJhtEmployerRate: 0.037,
    bpjsJkkRate: 0.0024,
    bpjsJkmRate: 0.003,
    bpjsJpEmployeeRate: 0.01,
    bpjsJpEmployerRate: 0.02,
    // PTKP 2024
    ptkpRates: {
        TK: 54000000,
        K0: 58500000,
        K1: 63000000,
        K2: 67500000,
        K3: 72000000,
    },
    defaultAnnualLeave: 12,
    nationalHolidays: [
        { date: '2026-01-01', name: 'Tahun Baru Masehi' },
        { date: '2026-01-29', name: 'Tahun Baru Imlek' },
        { date: '2026-03-20', name: 'Hari Raya Nyepi' },
        { date: '2026-03-29', name: 'Wafat Isa Al-Masih' },
        { date: '2026-04-07', name: 'Isra Miraj' },
        { date: '2026-05-01', name: 'Hari Buruh' },
        { date: '2026-05-14', name: 'Kenaikan Isa Al-Masih' },
        { date: '2026-06-01', name: 'Hari Lahir Pancasila' },
        { date: '2026-06-17', name: 'Hari Raya Idul Fitri' },
        { date: '2026-06-18', name: 'Hari Raya Idul Fitri' },
        { date: '2026-08-17', name: 'Hari Kemerdekaan RI' },
        { date: '2026-08-24', name: 'Hari Raya Idul Adha' },
        { date: '2026-09-14', name: 'Tahun Baru Hijriyah' },
        { date: '2026-11-23', name: 'Maulid Nabi Muhammad' },
        { date: '2026-12-25', name: 'Hari Natal' },
    ],
};

// ========================
// DEFAULT SHIFT TEMPLATES
// ========================

export const defaultShiftTemplates: ShiftTemplate[] = [
    {
        id: 'shift-regular',
        name: 'Regular',
        startTime: '08:00',
        endTime: '17:00',
        breakMinutes: 60,
        toleranceMinutes: 15,
        color: '#3b82f6', // blue
        isNightShift: false,
        workingHours: 8,
        isActive: true,
    },
    {
        id: 'shift-pagi',
        name: 'Shift Pagi',
        startTime: '06:00',
        endTime: '14:00',
        breakMinutes: 60,
        toleranceMinutes: 15,
        color: '#f59e0b', // amber
        isNightShift: false,
        workingHours: 7,
        isActive: true,
    },
    {
        id: 'shift-siang',
        name: 'Shift Siang',
        startTime: '14:00',
        endTime: '22:00',
        breakMinutes: 60,
        toleranceMinutes: 15,
        color: '#10b981', // green
        isNightShift: false,
        workingHours: 7,
        isActive: true,
    },
    {
        id: 'shift-malam',
        name: 'Shift Malam',
        startTime: '22:00',
        endTime: '06:00',
        breakMinutes: 60,
        toleranceMinutes: 15,
        color: '#6366f1', // indigo
        isNightShift: true,
        workingHours: 7,
        isActive: true,
    },
];

// ========================
// MOCK EMPLOYEES (ENHANCED)
// ========================

export const mockEmployees: Employee[] = [
    {
        id: '1',
        name: 'Budi Santoso',
        employeeId: 'EMP001',
        email: 'budi.santoso@worker.com',
        phone: '081234567890',
        position: 'Senior Developer',
        department: 'IT',
        joinDate: '2020-01-15',
        address: 'Jl. Sudirman No. 123, Jakarta',
        basicSalary: 15000000,
        allowances: { transport: 1000000, meal: 500000, other: 500000 },
        ktpNumber: '3174012501900001',
        npwp: '12.345.678.9-012.000',
        birthPlace: 'Jakarta',
        birthDate: '1990-01-25',
        gender: 'male',
        religion: 'Islam',
        bpjsKesId: 'BK-001234567',
        bpjsTkId: 'BTK-001234567',
        bankName: 'BCA',
        bankAccountNo: '1234567890',
        bankAccountName: 'Budi Santoso',
        maritalStatus: 'K1',
        dependents: 1,
        contractType: 'PKWTT',
        emergencyContact: { name: 'Sari Santoso', relationship: 'Istri', phone: '081234567899' },
        annualLeaveQuota: 12,
        usedLeaveQuota: 3,
        remainingLeaveQuota: 9,
        hierarchyLevel: 2,
        isApprover: true,
        latestPayrollId: undefined,
        status: 'active',
        skills: [
            { name: 'React', level: 'advanced', category: 'technical', lastUsed: '2024-12-01' },
            { name: 'TypeScript', level: 'intermediate', category: 'technical' },
            { name: 'Leadership', level: 'intermediate', category: 'softskill' },
        ],
        trainings: [
            { id: 't1', name: 'Advanced React Workshop', provider: 'ABC Training', startDate: '2023-05-10', endDate: '2023-05-12', status: 'completed', certificateId: 'c1' },
        ],
        certificates: [
            { id: 'c1', name: 'React Certificate', issuedBy: 'ABC Training', issueDate: '2023-05-12', expiryDate: null, valid: true },
        ],
    },
    {
        id: '2',
        name: 'Siti Nurhaliza',
        employeeId: 'EMP002',
        email: 'siti.nurhaliza@worker.com',
        phone: '081234567891',
        position: 'HR Manager',
        department: 'Human Resources',
        joinDate: '2019-03-20',
        address: 'Jl. Gatot Subroto No. 45, Jakarta',
        basicSalary: 12000000,
        allowances: { transport: 1000000, meal: 500000, other: 300000 },
        ktpNumber: '3174014503920002',
        npwp: '98.765.432.1-012.000',
        birthPlace: 'Bandung',
        birthDate: '1992-03-15',
        gender: 'female',
        religion: 'Islam',
        bpjsKesId: 'BK-002345678',
        bpjsTkId: 'BTK-002345678',
        bankName: 'Mandiri',
        bankAccountNo: '0987654321',
        bankAccountName: 'Siti Nurhaliza',
        maritalStatus: 'TK',
        dependents: 0,
        contractType: 'PKWTT',
        emergencyContact: { name: 'Ahmad Nurhaliza', relationship: 'Ayah', phone: '081234567898' },
        annualLeaveQuota: 12,
        usedLeaveQuota: 0,
        remainingLeaveQuota: 12,
        hierarchyLevel: 3,
        isApprover: true,
        latestPayrollId: undefined,
        status: 'active',
        skills: [
            { name: 'People Management', level: 'expert', category: 'softskill' },
            { name: 'Recruitment', level: 'advanced', category: 'softskill' },
            { name: 'Labor Law', level: 'advanced', category: 'technical' },
        ],
        trainings: [
            { id: 't2', name: 'Leadership Program', provider: 'HR Academy', startDate: '2022-08-01', endDate: '2022-08-05', status: 'completed' },
        ],
        certificates: [
            { id: 'c2', name: 'HR Certification', issuedBy: 'HR Institute', issueDate: '2022-08-06', expiryDate: '2025-08-06', valid: true },
        ],
    },
    {
        id: '3',
        name: 'Ahmad Yani',
        employeeId: 'EMP003',
        email: 'ahmad.yani@worker.com',
        phone: '081234567892',
        position: 'Marketing Executive',
        department: 'Marketing',
        joinDate: '2021-06-10',
        address: 'Jl. Thamrin No. 78, Jakarta',
        basicSalary: 8000000,
        allowances: { transport: 800000, meal: 500000, other: 200000 },
        ktpNumber: '3174011206950003',
        npwp: '55.666.777.8-012.000',
        birthPlace: 'Surabaya',
        birthDate: '1995-06-12',
        gender: 'male',
        religion: 'Islam',
        bpjsKesId: 'BK-003456789',
        bpjsTkId: 'BTK-003456789',
        bankName: 'BNI',
        bankAccountNo: '1122334455',
        bankAccountName: 'Ahmad Yani',
        maritalStatus: 'TK',
        dependents: 0,
        contractType: 'PKWT',
        contractEndDate: '2026-12-31',
        emergencyContact: { name: 'Dewi Yani', relationship: 'Ibu', phone: '081234567897' },
        annualLeaveQuota: 12,
        usedLeaveQuota: 0,
        remainingLeaveQuota: 12,
        hierarchyLevel: 1,
        isApprover: false,
        latestPayrollId: undefined,
        status: 'active',
        skills: [
            { name: 'Digital Marketing', level: 'intermediate', category: 'technical' },
            { name: 'Social Media', level: 'advanced', category: 'technical' },
            { name: 'English', level: 'intermediate', category: 'language' },
        ],
        trainings: [],
        certificates: [],
    },
    {
        id: '4',
        name: 'Dewi Lestari',
        employeeId: 'EMP004',
        email: 'dewi.lestari@worker.com',
        phone: '081234567893',
        position: 'Finance Manager',
        department: 'Finance',
        joinDate: '2018-07-01',
        address: 'Jl. Kuningan No. 22, Jakarta',
        basicSalary: 18000000,
        allowances: { transport: 1500000, meal: 750000, other: 750000 },
        ktpNumber: '3174010107880004',
        npwp: '33.444.555.6-012.000',
        birthPlace: 'Yogyakarta',
        birthDate: '1988-07-01',
        gender: 'female',
        religion: 'Kristen',
        bpjsKesId: 'BK-004567890',
        bpjsTkId: 'BTK-004567890',
        bankName: 'BCA',
        bankAccountNo: '5566778899',
        bankAccountName: 'Dewi Lestari',
        maritalStatus: 'K2',
        dependents: 2,
        contractType: 'PKWTT',
        emergencyContact: { name: 'Rudi Lestari', relationship: 'Suami', phone: '081234567896' },
        annualLeaveQuota: 12,
        usedLeaveQuota: 2,
        remainingLeaveQuota: 10,
        hierarchyLevel: 3,
        isApprover: true,
        latestPayrollId: undefined,
        status: 'active',
        skills: [
            { name: 'Financial Analysis', level: 'expert', category: 'technical' },
            { name: 'Excel', level: 'expert', category: 'technical' },
            { name: 'SAP', level: 'advanced', category: 'technical' },
            { name: 'Team Management', level: 'advanced', category: 'softskill' },
        ],
        trainings: [],
        certificates: [
            { id: 'c3', name: 'CFA Level 1', issuedBy: 'CFA Institute', issueDate: '2019-06-15', expiryDate: null, valid: true },
        ],
    },
    {
        id: '5',
        name: 'Eko Prasetyo',
        employeeId: 'EMP005',
        email: 'eko.prasetyo@worker.com',
        phone: '081234567894',
        position: 'Operations Staff',
        department: 'Operations',
        joinDate: '2023-02-01',
        address: 'Jl. Casablanca No. 88, Jakarta',
        basicSalary: 6500000,
        allowances: { transport: 600000, meal: 500000, other: 150000 },
        ktpNumber: '3174010302970005',
        npwp: '11.222.333.4-012.000',
        birthPlace: 'Semarang',
        birthDate: '1997-02-03',
        gender: 'male',
        religion: 'Islam',
        bpjsKesId: 'BK-005678901',
        bpjsTkId: 'BTK-005678901',
        bankName: 'BRI',
        bankAccountNo: '6677889900',
        bankAccountName: 'Eko Prasetyo',
        maritalStatus: 'K0',
        dependents: 0,
        contractType: 'PKWT',
        contractEndDate: '2026-07-31',
        emergencyContact: { name: 'Retno Prasetyo', relationship: 'Ibu', phone: '081234567895' },
        annualLeaveQuota: 12,
        usedLeaveQuota: 1,
        remainingLeaveQuota: 11,
        hierarchyLevel: 1,
        isApprover: false,
        latestPayrollId: undefined,
        status: 'active',
        skills: [
            { name: 'Warehouse Management', level: 'intermediate', category: 'technical' },
            { name: 'Forklift Operation', level: 'advanced', category: 'certification' },
        ],
        trainings: [],
        certificates: [
            { id: 'c4', name: 'SIO Forklift', issuedBy: 'Disnaker', issueDate: '2023-03-01', expiryDate: '2026-03-01', valid: true },
        ],
    },
];

export const mockLeaveRequests: LeaveRequest[] = [
    {
        id: '1',
        employeeId: '1',
        employeeName: 'Budi Santoso',
        leaveType: 'annual',
        startDate: '2024-02-01',
        endDate: '2024-02-03',
        totalDays: 3,
        reason: 'Liburan keluarga',
        status: 'approved',
        approver1Name: 'Manager',
        approver1Status: 'approved',
        approver1Date: '2024-01-25',
        approver2Name: 'HR Director',
        approver2Status: 'approved',
        approver2Date: '2024-01-26',
        createdAt: '2024-01-20',
    },
];

export const mockKPIs: KPI[] = [
    {
        id: '1',
        employeeId: '1',
        employeeName: 'Budi Santoso',
        kpiName: 'Project Completion',
        target: 10,
        actual: 12,
        unit: 'projects',
        weight: 40,
        period: '2024-01',
        createdAt: '2024-01-31',
    },
    {
        id: '2',
        employeeId: '1',
        employeeName: 'Budi Santoso',
        kpiName: 'Code Quality (Bug Rate)',
        target: 5,
        actual: 3,
        unit: 'bugs/sprint',
        weight: 30,
        period: '2024-01',
        createdAt: '2024-01-31',
    },
    {
        id: '3',
        employeeId: '2',
        employeeName: 'Siti Nurhaliza',
        kpiName: 'Employee Satisfaction',
        target: 85,
        actual: 90,
        unit: '%',
        weight: 50,
        period: '2024-01',
        createdAt: '2024-01-31',
    },
];

export const mockPayrollRecords: PayrollRecord[] = [];

export const mockDailyAttendance: DailyAttendance[] = [
    {
        id: '1',
        employeeId: '1',
        employeeName: 'Budi Santoso',
        date: new Date().toISOString().slice(0, 10),
        checkIn: null,
        checkOut: null,
        status: 'not_checked_in',
        workHours: 0,
        regularHours: 0,
        overtimeHours: 0,
        notes: '',
        createdAt: new Date().toISOString(),
    },
    {
        id: '2',
        employeeId: '2',
        employeeName: 'Siti Nurhaliza',
        date: new Date().toISOString().slice(0, 10),
        checkIn: null,
        checkOut: null,
        status: 'not_checked_in',
        workHours: 0,
        regularHours: 0,
        overtimeHours: 0,
        notes: '',
        createdAt: new Date().toISOString(),
    },
    {
        id: '3',
        employeeId: '3',
        employeeName: 'Ahmad Yani',
        date: new Date().toISOString().slice(0, 10),
        checkIn: null,
        checkOut: null,
        status: 'not_checked_in',
        workHours: 0,
        regularHours: 0,
        overtimeHours: 0,
        notes: '',
        createdAt: new Date().toISOString(),
    },
    {
        id: '4',
        employeeId: '4',
        employeeName: 'Dewi Lestari',
        date: new Date().toISOString().slice(0, 10),
        checkIn: null,
        checkOut: null,
        status: 'not_checked_in',
        workHours: 0,
        regularHours: 0,
        overtimeHours: 0,
        notes: '',
        createdAt: new Date().toISOString(),
    },
    {
        id: '5',
        employeeId: '5',
        employeeName: 'Eko Prasetyo',
        date: new Date().toISOString().slice(0, 10),
        checkIn: null,
        checkOut: null,
        status: 'not_checked_in',
        workHours: 0,
        regularHours: 0,
        overtimeHours: 0,
        notes: '',
        createdAt: new Date().toISOString(),
    },
];

export const mockAnnouncements: Announcement[] = [
    {
        id: 'ann-1',
        title: 'Selamat Datang di WORKer HRMS v2.0',
        content: 'Sistem HRMS telah diperbarui dengan fitur-fitur baru termasuk Shift Management, Enhanced Payroll, Recruitment, dan banyak lagi. Silakan eksplorasi menu sidebar untuk mencoba fitur baru.',
        priority: 'important',
        isPinned: true,
        authorName: 'Admin HR',
        createdAt: new Date().toISOString(),
    },
];

export const defaultSkillRequirements: SkillRequirement[] = [
    { id: 'sr-1', position: 'Senior Developer', department: 'IT', skillName: 'React', requiredLevel: 'advanced', mandatory: true },
    { id: 'sr-2', position: 'Senior Developer', department: 'IT', skillName: 'TypeScript', requiredLevel: 'intermediate', mandatory: true },
    { id: 'sr-3', position: 'Senior Developer', department: 'IT', skillName: 'Leadership', requiredLevel: 'intermediate', mandatory: false },
    { id: 'sr-4', position: 'HR Manager', department: 'Human Resources', skillName: 'People Management', requiredLevel: 'expert', mandatory: true },
    { id: 'sr-5', position: 'HR Manager', department: 'Human Resources', skillName: 'Recruitment', requiredLevel: 'advanced', mandatory: true },
    { id: 'sr-6', position: 'HR Manager', department: 'Human Resources', skillName: 'Labor Law', requiredLevel: 'advanced', mandatory: true },
    { id: 'sr-7', position: 'Marketing Executive', department: 'Marketing', skillName: 'Digital Marketing', requiredLevel: 'intermediate', mandatory: true },
    { id: 'sr-8', position: 'Marketing Executive', department: 'Marketing', skillName: 'Social Media', requiredLevel: 'advanced', mandatory: true },
    { id: 'sr-9', position: 'Finance Manager', department: 'Finance', skillName: 'Financial Analysis', requiredLevel: 'expert', mandatory: true },
    { id: 'sr-10', position: 'Finance Manager', department: 'Finance', skillName: 'Excel', requiredLevel: 'advanced', mandatory: true },
    { id: 'sr-11', position: 'Operations Staff', department: 'Operations', skillName: 'Warehouse Management', requiredLevel: 'intermediate', mandatory: true },
];
